# Generated by Django 4.2.14 on 2024-11-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales',
            new_name='Booking',
        ),
    ]
