# Generated by Django 4.2.14 on 2024-11-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_sales_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice_number',
        ),
    ]
