# Generated by Django 4.2.14 on 2024-11-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_remove_booking_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='booking',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='shop',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_due',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PAID', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=100)),
                ('amount', models.FloatField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.booking')),
            ],
        ),
    ]
