# Generated by Django 4.2.14 on 2024-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_booking_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shop',
            field=models.CharField(max_length=10000),
        ),
    ]
