# Generated by Django 4.2.14 on 2024-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_alter_booking_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
