# Generated by Django 4.2.14 on 2024-11-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_customer_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rent_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
