# Generated by Django 4.2.14 on 2024-11-28 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_remove_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='advance_rent',
        ),
    ]
