# Generated by Django 5.1.3 on 2024-12-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_logo_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
