# Generated by Django 5.1.3 on 2024-12-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal', models.FileField(upload_to='logo')),
                ('white', models.FileField(upload_to='logo')),
                ('small', models.FileField(upload_to='logo')),
            ],
        ),
    ]
