# Generated by Django 5.1.3 on 2024-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='icon',
            field=models.FileField(null=True, upload_to='logo'),
        ),
    ]
